### ISSUE TITLE
ERROR: MethodError: no method matching getindex(::Knet.KnetArray{Float32,3}, ::Int64, ::Int64, ::UnitRange{Int64})

### ISSUE THREAD

**Issue by arkynoah** [denizyuret/Knet.jl#136] opened 2017-06-19 11:13 UTC
When I try to use (:) or (n:n+m) in index; let A is a KnetArray 
A[1,1,:]
I got the following error
ERROR: MethodError: no method matching getindex(::Knet.KnetArray{Float32,3}, ::Int64, ::Int64, ::UnitRange{Int64})

**Comment by ilkerkesen** [comment] 2017-06-19 11:22
We don't support indexing for N-D arrays currently. However, you can overcome most situations by inventing a new hacky workaround which consists of stacked reshape/permutedims operations. In your case,

```A = rand(Float32, 3, 4, 5)
desired = A[1,1,:]
a0 = reshape(A, 12, 5)
a1 = a0[1,:]
a1 == desired
```

**Comment by arkynoah** [comment] 2017-06-19 11:25
What about transforming Array, taking index, then retransform it to
KnatArray. Do you suggest that?

**Comment by ilkerkesen** [comment] 2017-06-19 11:28
It is also OK, but it will be slower.

**Comment by arkynoah** [comment] 2017-06-19 11:30
Does this operation can any how affect back propagation?

**Comment by denizyuret** [comment] 2017-10-19 16:37
It should not effect backprop, each of the operations involved is differentiable by AutoGrad.  This issue is a duplicate of https://github.com/denizyuret/Knet.jl/issues/32.

**Closed** 2017-12-24 15:49 UTC
Labels: enhancement
