### ISSUE TITLE
Julia 0.7 compatibility

### ISSUE THREAD

**Issue by GunnarFarneback** [denizyuret/Knet.jl#316] opened 2018-07-09 20:35 UTC
What is the situation of porting Knet to Julia 0.7? Is there work going on but not visible in this repository? Are there important dependencies that need to be ported first before it's worth trying Knet itself? I'm willing to help out if there's something an outsider can do.

**Comment by CarloLucibello** [comment] 2018-07-10 06:03
I think the priority is to get AutoGrad going https://github.com/denizyuret/AutoGrad.jl/pull/68

**Comment by denizyuret** [comment] 2018-07-10 12:38
There is some work started under AutoGrad/rened-j7 branch. My current
target is to get this done before JuliaCon (August). This requires some
substantial changes (hopefully simplifications) to broadcasting mechanisms
in both AutoGrad and KnetArrays.

**Comment by GunnarFarneback** [comment] 2018-07-12 06:52
Thanks. I'll look into the more straightforward deprecation warnings in Knet, starting with a femtocleaner run. I've patched up AutoGrad locally so it at least loads on 0.7, which should make it possible to cover more of the Knet code.

**Comment by GunnarFarneback** [comment] 2018-07-12 07:14
What is the status of the `.deprecated` directories? Femtocleaner happily does syntax upgrades there as well. Should those be included or excluded from a PR?

**Comment by rened** [comment] 2018-07-12 08:39
@GunnarFarneback FWIW, I have a branch with fixes for 0.7 which had most of its tests passing a couple of weeks ago: https://github.com/rened/Knet.jl/tree/j7

But of course this needs https://github.com/denizyuret/AutoGrad.jl/pull/68  or better https://github.com/denizyuret/AutoGrad.jl/tree/rened-j7

**Comment by GunnarFarneback** [comment] 2018-07-12 10:00
Nice, that takes it a long way. The main issues I see on your branches with current Julia, causing load errors, are:
* The `Pkg.installed` conditional functionality is broken with the new package manager.
* In AutoGrad `unfuse.jl` is not loaded and nothing else provides `broadcast_func` and `Broadcasted`. This is obviously related to the broadcasting redesign.

There are also some new deprecation warnings but those don't look too difficult to deal with.

**Comment by rened** [comment] 2018-07-12 11:32
It seems that we also need to move from `CUDArt.jl` to [CUDAdrv.jl](https://github.com/JuliaGPU/CUDAdrv.jl).

**Comment by denizyuret** [comment] 2018-07-12 15:09
The main roadblock in both AutoGrad and Knet is the broadcasting redesign.
Handled correctly 0.7 broadcasting should simplify the code a lot. I hope
to figure this out next week. There is a thread in the mailing list about
how to do this right.

The second priority is optional package loads. My preference is for these
packages to work with as few dependencies as possible, but make use of
optional dependencies if available. e.g. AutoGrad should load/work just
with Base, but define gradients for other functions if the user happens to
have their packages available. Requires.jl gives us some of this
functionality.

**Comment by denizyuret** [comment] 2018-08-14 13:15
The latest master supports Julia 0.7 and 1.0. Please test.

**Comment by denizyuret** [comment] 2018-08-14 13:55
Julia 1.0 is finally out and we have been working on getting AutoGrad and Knet compatible. Great thanks to everyone who contributed. Unfortunately the latest language updates broke everything from broadcasting to iteration, from the array interfaces to function declaration. So simple syntax updates were not sufficient and major code restructuring was needed in both packages. It took a lot longer than I anticipated but the latest commits on master finally pass the existing tests. I had to manually go over the  pull requests and will continue to do so to merge anything that was missed. Sorry for the chaos.

The latest tagged versions AutoGrad 0.1.0 and Knet 0.9.2 work with Julia 0.6 and are incompatible with 0.7.  I will tag the new releases compatible with Julia 0.7-1.0 (not backwardly compatible with 0.6) starting with 1.0.0 and use semantic versioning going forward.

Before an official release for 1.0 is tagged I need help (in the form of pull requests) with the following:

1. Unit tests: each file under src should have a corresponding file under test that does unit testing of every function defined. Currently this is very incomplete especially for AutoGrad.

2. Documentation and Examples: These haven't been updated or tested. Julia 1.0 changed a lot of syntax and they need to be updated. I found Julia 0.7 helpful with its warnings in figuring out how to update the code.

3. Existing PRs and Issues: Some of the Issues may have been resolved, they need to be closed.  Most of the PRs will not merge with the new code, if they are still useful they need to be manually tested and merged.

To avoid duplication of effort, you can respond to this thread on the knet-dev list indicating what item(s) you plan to work on. AutoGrad/Knet is developed by volunteers and any contribution is appreciated.

**Comment by CarloLucibello** [comment] 2018-08-14 14:14
Knet is failing on a gpu node with julia 0.7 on linux.

Having completely removed Knet, i checkout the master branch with 
```
(v0.7) pkg> dev  Knet
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/denizyuret/Knet.jl.git`
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
  [1902f260] + Knet v0.9.2+ [`~/.julia/dev/Knet`]
  Updating `~/.julia/environments/v0.7/Manifest.toml`
  [1902f260] + Knet v0.9.2+ [`~/.julia/dev/Knet`]
  Building Knet → `~/.julia/dev/Knet/deps/build.log`
```
The build seems succesful, here is the log:
```
[lucibello@bidsa-sc ~]$ cat ~/.julia/dev/Knet/deps/build.log
cuda1.cu(628): warning: variable "xi" was set but never used

cuda1.cu(641): warning: variable "xi" was set but never used

cuda1.cu(940): warning: variable "xi" was set but never used

cuda1.cu(953): warning: variable "xi" was set but never used

cuda1.cu(628): warning: variable "xi" was set but never used

cuda1.cu(641): warning: variable "xi" was set but never used

cuda1.cu(940): warning: variable "xi" was set but never used

cuda1.cu(953): warning: variable "xi" was set but never used

[ Info: cuda1.jl
[ Info: `/usr/local/cuda-8.0/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir /usr/bin/gcc --compiler-options '-O3 -Wall -fPIC -fopenmp' -c cuda1.cu`
[ Info: cuda01.jl
[ Info: `/usr/local/cuda-8.0/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir /usr/bin/gcc --compiler-options '-O3 -Wall -fPIC -fopenmp' -c cuda01.cu`
[ Info: cuda11.jl
[ Info: `/usr/local/cuda-8.0/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir /usr/bin/gcc --compiler-options '-O3 -Wall -fPIC -fopenmp' -c cuda11.cu`
[ Info: cuda12.jl
[ Info: `/usr/local/cuda-8.0/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir /usr/bin/gcc --compiler-options '-O3 -Wall -fPIC -fopenmp' -c cuda12.cu`
[ Info: cuda13.jl
[ Info: `/usr/local/cuda-8.0/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir /usr/bin/gcc --compiler-options '-O3 -Wall -fPIC -fopenmp' -c cuda13.cu`
[ Info: cuda16.jl
[ Info: `/usr/local/cuda-8.0/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir /usr/bin/gcc --compiler-options '-O3 -Wall -fPIC -fopenmp' -c cuda16.cu`
[ Info: cuda17.jl
[ Info: `/usr/local/cuda-8.0/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir /usr/bin/gcc --compiler-options '-O3 -Wall -fPIC -fopenmp' -c cuda17.cu`
[ Info: cuda20.jl
[ Info: `/usr/local/cuda-8.0/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir /usr/bin/gcc --compiler-options '-O3 -Wall -fPIC -fopenmp' -c cuda20.cu`
[ Info: cuda21.jl
[ Info: `/usr/local/cuda-8.0/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir /usr/bin/gcc --compiler-options '-O3 -Wall -fPIC -fopenmp' -c cuda21.cu`
[ Info: cuda22.jl
[ Info: `/usr/local/cuda-8.0/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir /usr/bin/gcc --compiler-options '-O3 -Wall -fPIC -fopenmp' -c cuda22.cu`
[ Info: `/usr/local/cuda-8.0/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir /usr/bin/gcc --compiler-options '-O3 -Wall -fPIC -fopenmp' -c conv.cpp`
[ Info: `/usr/local/cuda-8.0/bin/nvcc -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir /usr/bin/gcc --compiler-options '-O3 -Wall -fPIC -fopenmp' --shared -o libknet8.so cuda1.o cuda01.o cuda11.o cuda12.o cuda13.o cuda16.o cuda17.o cuda20.o cuda21.o cuda22.o conv.o`
[ Info: Compiling Knet cache.
```
Then, while testing I get the following error:
```julia
v0.7) pkg> test Knet
   Testing Knet
 Resolving package versions...
    Status `/tmp/tmpgtqxGr/Manifest.toml`
    ....
Test Summary: | Pass  Total
kptr          |    1      1
 11.000435 seconds (18.26 M allocations: 909.246 MiB, 8.04% gc time)
(Knet.cudaDriverVersion, Knet.cudaRuntimeVersion, Knet.cublasVersion, Knet.cudnnVersion) = (8000, 8000, 8000, 6021)
(Knet.nvmlDriverVersion, Knet.nvmlVersion) = ("375.51", "8.375.51")
Test Summary: | Pass  Total
gpu           |    8      8
  3.693692 seconds (1.96 M allocations: 97.261 MiB, 3.51% gc time)
Test Summary: | Pass  Total
distributions |    3      3
  1.832136 seconds (3.92 M allocations: 194.378 MiB, 5.04% gc time)
dropout: Error During Test at /home/lucibello/.julia/dev/Knet/test/dropout.jl:9
  Test threw exception ErrorException("Cannot find libknet8, please rerun Pkg.build(\"Knet\").")
  Expression: gradcheck(dropout1, k, 0.5)
  Cannot find libknet8, please rerun Pkg.build("Knet").
  Stacktrace:
   [1] error(::String) at ./error.jl:33
   [2] dropout!(::Float64, ::KnetArray{Float64,2}, ::KnetArray{Float64,2}) at /home/lucibello/.julia/dev/Knet/src/drop
out.jl:57
   [3] #dropout#652(::Int64, ::Function, ::KnetArray{Float64,2}, ::Float64) at /home/lucibello/.julia/dev/Knet/src/dro
pout.jl:22
.......
It could simply be a path related problem?

**Comment by denizyuret** [comment] 2018-08-14 14:26
The build seems normal but `ErrorException("Cannot find libknet8, please
rerun Pkg.build(\"Knet\").` indicates it cannot find libknet8.so.  Can you
try `pkg> build Knet` and `pkg> precompile` one more time?

**Comment by CarloLucibello** [comment] 2018-08-14 14:27
tests are passing on a cpu-only box but I still get a lot of warnings
```julia
Test Summary: | Pass  Total
kptr          |    1      1
 17.006503 seconds (17.12 M allocations: 851.134 MiB, 2.30% gc time)
  0.637037 seconds (45.90 k allocations: 2.515 MiB, 0.70% gc time)
Test Summary: | Pass  Total
distributions |    3      3
  1.600978 seconds (3.92 M allocations: 194.544 MiB, 3.15% gc time)
Test Summary: | Pass  Total
dropout       |    1      1
  1.649890 seconds (3.24 M allocations: 165.413 MiB, 2.74% gc time)
Test Summary: | Pass  Total
loss          |    6      6
  4.645045 seconds (10.17 M allocations: 509.414 MiB, 3.94% gc time)
┌ Warning: Deprecated syntax `implicit assignment to global variable `r``.
│ Use `global r` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `w``.
│ Use `global w` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `rcpu``.
│ Use `global rcpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `wcpu``.
│ Use `global wcpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `wcpu``.
│ Use `global wcpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `x1cpu``.
│ Use `global x1cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `x1``.
│ Use `global x1` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx1cpu``.
│ Use `global hx1cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx1``.
│ Use `global hx1` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx1cpu``.
│ Use `global cx1cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx1``.
│ Use `global cx1` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `x2cpu``.
│ Use `global x2cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `x2``.
│ Use `global x2` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx2cpu``.
│ Use `global hx2cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx2``.
│ Use `global hx2` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx2cpu``.
│ Use `global cx2cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx2``.
│ Use `global cx2` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `x3cpu``.
│ Use `global x3cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `x3``.
│ Use `global x3` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx3cpu``.
│ Use `global hx3cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx3``.
│ Use `global hx3` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx3cpu``.
│ Use `global cx3cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx3``.
│ Use `global cx3` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx2``.
│ Use `global hx2` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx2``.
│ Use `global cx2` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx3``.
│ Use `global hx3` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx3``.
│ Use `global cx3` instead.
└ @ none:0
  1.453361 seconds (1.02 M allocations: 50.235 MiB, 1.09% gc time)
  0.779931 seconds (34.22 k allocations: 2.229 MiB)
┌ Warning: Deprecated syntax `implicit assignment to global variable `w``.
│ Use `global w` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `w``.
│ Use `global w` instead.
└ @ none:0
┌ Warning: `isbits(#= deprecated.jl:1691 =# @nospecialize(t::Type))` is deprecated, use `isbitstype(t)` instead.
│   caller = update!(::Tuple{Array{Float64,1},Array{Float64,1}}, ::Tuple{Array{Float64,1},Array{Float64,1}}, ::Tuple{Adam,Adam}) at update.jl:439
└ @ Knet ~/.julia/dev/Knet/src/update.jl:439
┌ Warning: `isbits(#= deprecated.jl:1691 =# @nospecialize(t::Type))` is deprecated, use `isbitstype(t)` instead.
│   caller = update!(::Array{Any,1}, ::Array{Any,1}, ::Array{Adam,1}) at update.jl:439
└ @ Knet ~/.julia/dev/Knet/src/update.jl:439
Test Summary: | Pass  Total
update!       |   10     10
 14.160610 seconds (40.75 M allocations: 1.988 GiB, 3.31% gc time)
Test Summary: | Pass  Total
conv          |   52     52
 29.454153 seconds (53.00 M allocations: 2.561 GiB, 2.86% gc time)
┌ Warning: Deprecated syntax `implicit assignment to global variable `r``.
│ Use `global r` instead.
└ @ none:0
Test Summary: | Pass  Total
linalg        |   64     64
 25.007551 seconds (49.65 M allocations: 2.355 GiB, 3.69% gc time)
10:21:33 broadcast: array-scalar 
10:22:20 broadcast: array-vector 
10:22:46 broadcast: array-array 
Test Summary: | Pass  Total
broadcast     | 1256   1256
10:22:51 broadcast: done 
 78.479136 seconds (139.31 M allocations: 7.150 GiB, 4.13% gc time)
┌ Warning: Deprecated syntax `implicit assignment to global variable `ax``.
│ Use `global ax` instead.
└ @ none:0
Test Summary: | Pass  Total
unary         |  672    672
117.363894 seconds (176.34 M allocations: 8.485 GiB, 4.90% gc time)
┌ Warning: Deprecated syntax `implicit assignment to global variable `ax``.
│ Use `global ax` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `ax``.
│ Use `global ax` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `ax``.
│ Use `global ax` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `ax``.
│ Use `global ax` instead.
└ @ none:0
Test Summary: | Pass  Total
reduction     |  508    508
 55.932902 seconds (96.19 M allocations: 4.588 GiB, 6.14% gc time)
┌ Warning: Deprecated syntax `implicit assignment to global variable `ax``.
│ Use `global ax` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `aw``.
│ Use `global aw` instead.
└ @ none:0
Test Summary: | Pass  Total
batchnorm     |   56     56
 43.364812 seconds (81.89 M allocations: 3.844 GiB, 7.03% gc time)
   Testing Knet tests passed 
```

**Comment by CarloLucibello** [comment] 2018-08-14 14:35
building again did the trick. On the first test run I got the following error though:
```julia
Test Summary: | Pass  Total
kptr          |    1      1
 21.798245 seconds (18.76 M allocations: 934.705 MiB, 3.53% gc time)
(Knet.cudaDriverVersion, Knet.cudaRuntimeVersion, Knet.cublasVersion, Knet.cudnnVersion) = (8000, 8000, 8000, 6021)
(Knet.nvmlDriverVersion, Knet.nvmlVersion) = ("375.51", "8.375.51")
Test Summary: | Pass  Total
gpu           |    8      8
  3.829045 seconds (1.96 M allocations: 97.724 MiB, 3.32% gc time)
Test Summary: | Pass  Total
distributions |    3      3
  1.835564 seconds (3.92 M allocations: 194.398 MiB, 4.60% gc time)
dropout: Test Failed at /home/lucibello/.julia/dev/Knet/test/dropout.jl:12
  Expression: isapprox(sum(abs2, dropout1(k, 0.5)), sum(abs2, dropout1(a, 0.5)), rtol=0.01)
   Evaluated: isapprox(6719.47139953436, 6623.054489924889; rtol=0.01)
Stacktrace:
 [1] macro expansion at /home/lucibello/.julia/dev/Knet/test/dropout.jl:12 [inlined]
 [2] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:1079 [i
nlined]
 [3] top-level scope at /home/lucibello/.julia/dev/Knet/test/dropout.jl:4
Test Summary: | Pass  Fail  Total
dropout       |    2     1      3
ERROR: LoadError: LoadError: Some tests did not pass: 2 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /home/lucibello/.julia/dev/Knet/test/dropout.jl:3
in expression starting at /home/lucibello/.julia/dev/Knet/test/runtests.jl:6
ERROR: Package Knet errored during testing
```
I'm testing again and that test is passing now, but it seems to be hanging in the `update!` testset, it's been a few minutes, I don't know if that s normal

**Comment by CarloLucibello** [comment] 2018-08-14 15:33
`update!` testset took 36 minutes. Is that a performance regression?

Also I get an `lmul!` not defined error:

```julia
Test Summary: | Pass  Total
kptr          |    1      1
 10.787147 seconds (18.27 M allocations: 909.632 MiB, 7.54% gc time)
(Knet.cudaDriverVersion, Knet.cudaRuntimeVersion, Knet.cublasVersion, Knet.cudnnVersion) = (8000, 8000, 8000, 6021)
(Knet.nvmlDriverVersion, Knet.nvmlVersion) = ("375.51", "8.375.51")
Test Summary: | Pass  Total
gpu           |    8      8
  3.797458 seconds (1.96 M allocations: 97.262 MiB, 3.28% gc time)
Test Summary: | Pass  Total
distributions |    3      3
  1.823788 seconds (3.92 M allocations: 194.371 MiB, 5.04% gc time)
Test Summary: | Pass  Total
dropout       |    3      3
  4.089773 seconds (6.07 M allocations: 306.979 MiB, 2.74% gc time)
Test Summary: | Pass  Total
loss          |   18     18
 11.415685 seconds (16.77 M allocations: 835.495 MiB, 3.99% gc time)
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx1``.
│ Use `global hx1` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx1cpu``.
│ Use `global cx1cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx1``.
│ Use `global cx1` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `x2cpu``.
│ Use `global x2cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `x2``.
│ Use `global x2` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx2cpu``.
│ Use `global hx2cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx2``.
│ Use `global hx2` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx2cpu``.
│ Use `global cx2cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx2``.
│ Use `global cx2` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `x3cpu``.
│ Use `global x3cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `x3``.
│ Use `global x3` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx3cpu``.
│ Use `global hx3cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx3``.
│ Use `global hx3` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx3cpu``.
│ Use `global cx3cpu` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx3``.
│ Use `global cx3` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `hx2``.
│ Use `global hx2` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `cx2``.
│ Use `global cx2` instead.
Test Summary: | Pass  Total
rnn           | 1776   1776
418.418262 seconds (106.68 M allocations: 9.145 GiB, 0.92% gc time)
Test Summary: | Pass  Total
karray        |  240    240
 62.203276 seconds (82.49 M allocations: 3.913 GiB, 3.20% gc time)
┌ Warning: Deprecated syntax `implicit assignment to global variable `w``.
│ Use `global w` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `w``.
│ Use `global w` instead.
└ @ none:0
┌ Warning: `isbits(#= deprecated.jl:1691 =# @nospecialize(t::Type))` is deprecated, use `isbitstype(t)` instead.
│   caller = update!(::Tuple{Array{Float64,1},Array{Float64,1}}, ::Tuple{Array{Float64,1},Array{Float64,1}}, ::Tuple{A
dam,Adam}) at update.jl:439
└ @ Knet ~/.julia/dev/Knet/src/update.jl:439
┌ Warning: `isbits(#= deprecated.jl:1691 =# @nospecialize(t::Type))` is deprecated, use `isbitstype(t)` instead.
│   caller = update!(::Array{Any,1}, ::Array{Any,1}, ::Array{Adam,1}) at update.jl:439
└ @ Knet ~/.julia/dev/Knet/src/update.jl:439

┌ Warning: `isbits(#= deprecated.jl:1691 =# @nospecialize(t::Type))` is deprecated, use `isbitstype(t)` instead.
│   caller = update!(::Tuple{KnetArray{Float64,1},KnetArray{Float64,1}}, ::Tuple{KnetArray{Float64,1},KnetArray{Float6
4,1}}, ::Tuple{Adam,Adam}) at update.jl:439
└ @ Knet ~/.julia/dev/Knet/src/update.jl:439
Test Summary: | Pass  Total
update!       |   20     20
2193.592259 seconds (69.91 M allocations: 3.215 GiB, 0.14% gc time)
Test Summary: | Pass  Total
conv          |  138    138
126.940742 seconds (113.00 M allocations: 5.470 GiB, 14.46% gc time)
┌ Warning: Deprecated syntax `implicit assignment to global variable `kd``.
│ Use `global kd` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `r``.
│ Use `global r` instead.
└ @ none:0
linalg: Error During Test at /home/lucibello/.julia/dev/Knet/test/linalg.jl:27
  Test threw exception UndefVarError(:lmul!)
  Expression: isapprox(lmul!(r, d), lmul!(r, kd))
  UndefVarError: lmul! not defined
  Stacktrace:
[1] macro expansion at /home/lucibello/.julia/dev/Knet/test/linalg.jl:27 [inlined]
   [2] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:1079 
[inlined]
   [3] top-level scope at /home/lucibello/.julia/dev/Knet/test/linalg.jl:7
linalg: Error During Test at /home/lucibello/.julia/dev/Knet/test/linalg.jl:28
  Test threw exception UndefVarError(:rmul!)
  Expression: isapprox(rmul!(d, r), rmul!(kd, r))
  UndefVarError: rmul! not defined
  Stacktrace:
   [1] macro expansion at /home/lucibello/.julia/dev/Knet/test/linalg.jl:28 [inlined]
   [2] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:1079 
[inlined]
   [3] top-level scope at /home/lucibello/.julia/dev/Knet/test/linalg.jl:7
linalg: Error During Test at /home/lucibello/.julia/dev/Knet/test/linalg.jl:27
  Test threw exception UndefVarError(:lmul!)
  Expression: isapprox(lmul!(r, d), lmul!(r, kd))
  UndefVarError: lmul! not defined
  Stacktrace:
   [1] macro expansion at /home/lucibello/.julia/dev/Knet/test/linalg.jl:27 [inlined]
   [2] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:1079 
[inlined]
   [3] top-level scope at /home/lucibello/.julia/dev/Knet/test/linalg.jl:7
linalg: Error During Test at /home/lucibello/.julia/dev/Knet/test/linalg.jl:28
  Test threw exception UndefVarError(:rmul!)
  Expression: isapprox(rmul!(d, r), rmul!(kd, r))
  UndefVarError: rmul! not defined
  Stacktrace:
   [1] macro expansion at /home/lucibello/.julia/dev/Knet/test/linalg.jl:28 [inlined]
   [2] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:1079 
[inlined]
   [3] top-level scope at /home/lucibello/.julia/dev/Knet/test/linalg.jl:7
Test Summary: | Pass  Error  Total
linalg        |  182      4    186
ERROR: LoadError: LoadError: Some tests did not pass: 182 passed, 0 failed, 4 errored, 0 broken.
in expression starting at /home/lucibello/.julia/dev/Knet/test/linalg.jl:6
in expression starting at /home/lucibello/.julia/dev/Knet/test/runtests.jl:12
ERROR: Package Knet errored during testing
```

**Comment by denizyuret** [comment] 2018-08-14 15:39
Is this Julia 0.7 or 1.0?

**Comment by CarloLucibello** [comment] 2018-08-14 15:51
it's on julia 0.7
I fixed the problem adding `using LinearAlgebra: lmul!, rmul!` to
test/linalg.jl
All tests seem to be passing now, still have to finish though

Il giorno mar 14 ago 2018 alle ore 11:39 denizyuret <
notifications@github.com> ha scritto:

**Comment by denizyuret** [comment] 2018-08-14 15:54
I am not getting the "Warning: Deprecated syntax `implicit assignment to global variable `r`" warnings?

**Comment by CarloLucibello** [comment] 2018-08-14 15:56
weird, you should:
```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0 (2018-08-08 06:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> z=1
1

julia> for i=1:2
       z = i
       end
┌ Warning: Deprecated syntax `implicit assignment to global variable `z``.
│ Use `global z` instead.
└ @ none:0
```

**Comment by CarloLucibello** [comment] 2018-08-14 16:04
so the remaining tests are passing:
```
Test Summary: | Pass  Total
linalg        |  186    186
 90.096043 seconds (131.26 M allocations: 6.310 GiB, 4.06% gc time)
17:38:59 broadcast: array-scalar 
17:40:35 broadcast: array-vector 
17:42:47 broadcast: array-array 
17:43:02 broadcast: ndims 
Test Summary: | Pass  Total
broadcast     | 3779   3779
17:43:03 broadcast: done 
244.980710 seconds (212.68 M allocations: 10.710 GiB, 2.75% gc time)
Test Summary: | Pass  Total
unary         | 1680   1680
250.154545 seconds (273.68 M allocations: 13.119 GiB, 5.90% gc time)
Test Summary: | Pass  Total
reduction     | 1620   1620
175.081993 seconds (211.02 M allocations: 9.619 GiB, 7.54% gc time)
Test Summary: | Pass  Total
batchnorm     |  130    130
 98.579296 seconds (135.47 M allocations: 6.424 GiB, 9.80% gc time)
   Testing Knet tests passed 
```
Only things to fix I could spot are
- add `using LinearAlgebra: lmul!, rmul!` to
test/linalg.jl
- use `global` keyword in the for loops in tests
- update travis.yml (and even better add gpu testing through #312)

**Comment by CarloLucibello** [comment] 2018-08-14 17:44
> Slimming down the tests is a good idea. But 36 minutes should not happen. Was that on a cpu? None of my tests take longer than 3 minutes on a K80.

On a gpu node with a K40, but I just realized other people are using it (which I was assuming it wasn't even possible with knet), so I guess this explains why it is so slow

**Closed** 2018-08-22 20:18 UTC
